Fix/uppsf 2749 migrate to cmneo4j
Financial-Times/content-rw-neo4j pull request #51
Opened 2021-10-21 07:32 UTC by mchompalova

# Description

## What

We migrated content-rw-neo4j to the new cm-neo4j-driver.

## Why

https://financialtimes.atlassian.net/browse/UPPSF-2749

## Scope and particulars of this PR (Please tick all that apply)

- [x] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [x] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2021-11-01 09:22 UTC, mchompalova commented on content/content_service.go
>  			MERGE(c)<-[rel:IS_CURATED_FOR]-(sp)`
Fixed.

2021-11-01 09:26 UTC, mchompalova commented on content/content_service.go
>  			MERGE(c)-[rel:CONTAINS]->(cp)`
Fixed.

2021-11-01 09:31 UTC, mchompalova commented on content/content_service_test.go
>  		MERGE (content)-[pred:SOME_PPREDICATE]->(concept)
Fixed.

2021-11-01 09:32 UTC, mchompalova commented on content/content_service_test.go
>  		RETURN count(r) as c`
Fixed.

2021-11-01 09:33 UTC, mchompalova commented on content/content_service_test.go
>  		RETURN count(r) as c`
Fixed.

2021-11-01 09:36 UTC, mchompalova commented on content/content_service_test.go
>  			RETURN t.uuid
Fixed.

2021-11-01 10:38 UTC, mchompalova commented on content/content_service.go
>  	}
Fixed.

2021-11-01 14:13 UTC, mchompalova commented on content/content_service_test.go
>  	assert.Equal("Thing", result[0].NodeLabels[0], "Thing should be the grandparent label")
Fixed.

2021-11-01 14:13 UTC, mchompalova commented on content/content_service_test.go
>  	assert.Equal("Thing", result[0].NodeLabels[0], "Thing should be the parent label")
Fixed.

2021-11-02 07:21 UTC, ivanruski commented on content/content_service_test.go
>  		MERGE (concept:Thing) ON CREATE SET concept.uuid = {conceptId}
This one should be updated as well.

> ```suggestion

		MERGE (concept:Thing) ON CREATE SET concept.uuid = $conceptId
```

2021-11-02 07:23 UTC, ivanruski requested changes
Just one more thing needs to be changed.

2021-11-02 08:17 UTC, ivanruski submitted a review, later dismissed
LGTM

2021-11-02 15:31 UTC, ManoelMilchev approved these changes

2021-11-05 11:45 UTC, ManoelMilchev submitted a review, later dismissed
LGTM

2021-11-05 12:29 UTC, ManoelMilchev approved these changes

2021-11-05 16:02 UTC, ivanruski approved these changes

2021-11-08 12:10 UTC, merged